# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, jar, src ]
  pull_request:
    branches: [ master, jar, src ]
  watch:
    types: [ started ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: github.actor == github.event.repository.owner.login

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Compose workspace
      uses: sifive/wit/actions/wit@master
      with:
        command: init
        arguments: |
          workspace
          -a git@github.com:davidmlw/example-chisel-iotester-wake.git::jar
        force_github_https: true

    - name: Build workspace
      uses: davidmlw/jdk-wake@master
      with:
        arguments: all
